return {
  -- {
  --   'MeanderingProgrammer/markdown.nvim',
  --   main = 'render-markdown',
  --   name = 'render-markdown',
  --   enable = false,
  --   dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' },
  --   opts = {
  --     file_types = { 'markdown' },
  --     exclude = {
  --       buftypes = { 'nofile', 'prompt', 'terminal' },
  --     },
  --   },
  --   config = function(_, opts)
  --     require('render-markdown').setup(opts)
  --
  --     -- Extra safety: disable in floating windows
  --     vim.api.nvim_create_autocmd('BufEnter', {
  --       callback = function(args)
  --         local win = vim.fn.bufwinid(args.buf)
  --         if win ~= -1 then
  --           local config = vim.api.nvim_win_get_config(win)
  --           if config.relative ~= '' then
  --             vim.b[args.buf].render_markdown_enabled = false
  --           end
  --         end
  --       end,
  --     })
  --   end,
  -- },
  -- {
  --   'iamcco/markdown-preview.nvim',
  --   cmd = { 'MarkdownPreviewToggle', 'MarkdownPreview', 'MarkdownPreviewStop' },
  --   ft = { 'markdown' },
  --   build = function()
  --     vim.fn['mkdp#util#install']()
  --   end,
  --   enable = false,
  -- },
  -- {
  --   'epwalsh/obsidian.nvim',
  --   version = 'v3.9.0', -- recommended, use latest release instead of latest commit
  --   lazy = true,
  --   enable = false,
  --   ft = 'markdown',
  --   -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
  --   -- event = {
  --   --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
  --   --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/*.md"
  --   --   -- refer to `:h file-pattern` for more examples
  --   --   "BufReadPre path/to/my-vault/*.md",
  --   --   "BufNewFile path/to/my-vault/*.md",
  --   -- },
  --   dependencies = {
  --     -- Required.
  --     'nvim-lua/plenary.nvim',
  --
  --     -- see below for full list of optional dependencies 👇
  --   },
  --   opts = {
  --     workspaces = {
  --       {
  --         name = 'personal',
  --         path = '~/vaults/my-second-brain/',
  --       },
  --       {
  --         name = 'work',
  --         path = '~/vaults/work',
  --       },
  --     },
  --
  --     -- see below for full list of options 👇
  --   },
  -- },
}
